// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { WalletProvider } from "@/contexts/WalletContext";
// import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "CasperStake - Privacy-First Liquid Staking",
//   description: "Stake CSPR, receive csCSPR. Privacy-first liquid staking with ZK proofs, cross-chain bridge, and anonymous DAO voting.",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} bg-black text-white min-h-screen`}>
//         <WalletProvider>
//           <Navbar />
//           {/* Global Message Toast */}
//           <main>{children}</main>
//           {/* Footer */}
//           <footer className="border-t border-white/10 mt-16">
//             <div className="max-w-7xl mx-auto px-4 md:px-8 py-8">
//               <div className="grid md:grid-cols-4 gap-8 mb-8">
//                 <div>
//                   <div className="flex items-center gap-2 mb-4">
//                     <div className="w-8 h-8 bg-red-600 rounded flex items-center justify-center text-white font-black text-sm">CS</div>
//                     <span className="font-black text-xl">CasperStake</span>
//                   </div>
//                   <p className="text-gray-400 text-sm">Privacy-first liquid staking on Casper Network. Stake, earn, and maintain your privacy.</p>
//                 </div>
//                 <div>
//                   <h4 className="font-bold mb-4">Products</h4>
//                   <ul className="space-y-2 text-gray-400 text-sm">
//                     <li><a href="/stake" className="hover:text-white">Liquid Staking</a></li>
//                     <li><a href="/swap" className="hover:text-white">LST DEX</a></li>
//                     <li><a href="/bridge" className="hover:text-white">Cross-Chain Bridge</a></li>
//                     <li><a href="/privacy" className="hover:text-white">ZK Proofs</a></li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h4 className="font-bold mb-4">Resources</h4>
//                   <ul className="space-y-2 text-gray-400 text-sm">
//                     <li><a href="/analytics" className="hover:text-white">Analytics</a></li>
//                     <li><a href="https://docs.casper.network" target="_blank" className="hover:text-white">Docs</a></li>
//                     <li><a href="https://github.com" target="_blank" className="hover:text-white">GitHub</a></li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h4 className="font-bold mb-4">Community</h4>
//                   <ul className="space-y-2 text-gray-400 text-sm">
//                     <li><a href="https://twitter.com" target="_blank" className="hover:text-white">Twitter</a></li>
//                     <li><a href="https://discord.com" target="_blank" className="hover:text-white">Discord</a></li>
//                     <li><a href="https://t.me" target="_blank" className="hover:text-white">Telegram</a></li>
//                   </ul>
//                 </div>
//               </div>
//               <div className="border-t border-white/10 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
//                 <p className="text-gray-400 text-sm">© 2026 CasperStake. Built for Casper Hackathon 2026 🚀</p>
//                 <div className="flex gap-4 text-gray-400 text-sm">
//                   <span>5 Contracts Deployed</span>
//                   <span>•</span>
//                   <span>Testnet Live</span>
//                 </div>
//               </div>
//             </div>
//           </footer>
//         </WalletProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WalletProvider } from "@/contexts/WalletContext";
import Navbar from "@/components/Navbar";
import Toast from "@/components/Toast";
import ToastProvider from "@/components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CasperStake - Privacy-First Liquid Staking",
  description: "Stake CSPR, receive csCSPR. Privacy-first liquid staking with ZK proofs, cross-chain bridge, and anonymous DAO voting.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white min-h-screen`}>
        <WalletProvider>
          <ToastProvider>
          <Navbar />
          <Toast />
          <main>{children}</main>
          {/* Footer */}
          <footer className="border-t border-white/10 mt-16">
            <div className="max-w-7xl mx-auto px-4 md:px-8 py-8">
              <div className="grid md:grid-cols-4 gap-8 mb-8">
                <div>
                  <div className="flex items-center gap-2 mb-4">
                    <div className="w-8 h-8 bg-red-600 rounded flex items-center justify-center text-white font-black text-sm">CS</div>
                    <span className="font-black text-xl">CasperStake</span>
                  </div>
                  <p className="text-gray-400 text-sm">Privacy-first liquid staking on Casper Network. Stake, earn, and maintain your privacy.</p>
                </div>
                <div>
                  <h4 className="font-bold mb-4">Products</h4>
                  <ul className="space-y-2 text-gray-400 text-sm">
                    <li><a href="/stake" className="hover:text-white">Liquid Staking</a></li>
                    <li><a href="/swap" className="hover:text-white">LST DEX</a></li>
                    <li><a href="/bridge" className="hover:text-white">Cross-Chain Bridge</a></li>
                    <li><a href="/privacy" className="hover:text-white">ZK Proofs</a></li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-bold mb-4">Resources</h4>
                  <ul className="space-y-2 text-gray-400 text-sm">
                    <li><a href="/analytics" className="hover:text-white">Analytics</a></li>
                    <li><a href="https://docs.casper.network" target="_blank" className="hover:text-white">Docs</a></li>
                    <li><a href="https://github.com" target="_blank" className="hover:text-white">GitHub</a></li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-bold mb-4">Community</h4>
                  <ul className="space-y-2 text-gray-400 text-sm">
                    <li><a href="https://twitter.com" target="_blank" className="hover:text-white">Twitter</a></li>
                    <li><a href="https://discord.com" target="_blank" className="hover:text-white">Discord</a></li>
                    <li><a href="https://t.me" target="_blank" className="hover:text-white">Telegram</a></li>
                  </ul>
                </div>
              </div>
              <div className="border-t border-white/10 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
                <p className="text-gray-400 text-sm">© 2026 CasperStake. Built for Casper Hackathon 2026 🚀</p>
                <div className="flex gap-4 text-gray-400 text-sm">
                  <span>5 Contracts Deployed</span>
                  <span>•</span>
                  <span>Testnet Live</span>
                </div>
              </div>
            </div>
          </footer>
          </ToastProvider>
        </WalletProvider>
      </body>
    </html>
  );
}