name = "casper_stake_new"
ffi = "casper"

[[contracts]]
name = "CasperStake"
fqn = "casper_stake_fresh::casper_stake::CasperStake"

[[contracts]]
name = "CasperStakeBridge"
fqn = "casper_stake_fresh::casper_stake_bridge::CasperStakeBridge"

[[contracts]]
name = "CsCSPRToken"
fqn = "casper_stake_fresh::token::CsCSPRToken"

[[contracts]]
name = "PrivacyModule"
fqn = "casper_stake_fresh::privacy_module::PrivacyModule"

[[contracts]]
name = "ThresholdModule"
fqn = "casper_stake_fresh::threshold_module::ThresholdModule"

[[contracts]]
name = "InstitutionalVault"
fqn = "casper_stake_fresh::institutional_vault_zk::InstitutionalVault"
